version: "3.8"

services:
  postgres:
    image: postgres
    container_name: spring_postgres
    restart: always
    environment:
      POSTGRES_DB: aptagrim
      POSTGRES_USER: POSTGRES_DOCKER
      POSTGRES_PASSWORD: Abcd.1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
